---
abstract: 'Mojolicious plugin to interact with a remote ident service'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Ident
requires:
  Mojo::Base: 0
  Mojo::Exception: 0
  Net::Ident: 0
  Socket: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/plicease/Mojolicious-Plugin-Ident/issues
  repository: git://github.com/plicease/Mojolicious-Plugin-Ident.git
version: 0.1
